[workspace]
members = [
    "c2rust",
    "c2rust-transpile",
    "c2rust-refactor",
    "c2rust-ast-builder",
    "c2rust-ast-exporter",
    "manual/preprocessors",
    "analysis/plugin",
    "analysis/runtime",
    "analysis/test",
]
exclude = [
    "cross-checks/rust-checks",
    "examples",
]
