[package]
name = "c2rust-analysis-rt"
version = "0.1.0"
authors = ["The C2Rust Development Team <c2rust@immunant.com>",
           "Stephen Crane <sjc@immunant.com>"]
edition = "2018"

[lib]

[dependencies]
