[package]
name = "c2rust-refactor"
version = "0.9.0"
authors = [
  "The C2Rust Project Developers <c2rust@immunant.com>",
  "Stuart Pernsteiner <spernsteiner@galois.com>",
]
build = "build.rs"
license = "BSD-3-Clause"
homepage = "https://c2rust.com/"
repository = "https://github.com/immunant/c2rust"
description = "C2Rust refactoring tool implemenation"

[dependencies]
diff = "0.1.10"
json = "0.11.8"
libc = "0.2.28"
regex = "1.1.0"
ena = "0.11.0"
c2rust-ast-builder = { version = "0.9.0", path = "../c2rust-ast-builder" }
indexmap = { version = "1.0.1", features = ["serde-1"] }
cargo = "0.32.0"
clap = {version = "~2.32.0", features = ["yaml"]}
c2rust-analysis-rt = { path = "../analysis/runtime" }
error-chain = "0.12.0"
bincode = "1.0.1"

[lib]
name = "c2rust_refactor"
path = "src/lib.rs"
