[package]
name = "c2rust-dynamic-instrumentation"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bincode = "1.0.1"
c2rust-analysis-rt = { path = "../analysis/runtime"}
cargo = "0.62"
cargo-util = "0.1"
indexmap = "1.8"
lazy_static = "1.4"
log = "0.4"
env_logger = "0.9"
color-eyre = "0.6"
fs-err = "2"
clap = { version = "3.2", features = ["derive"] }
cargo_metadata = "0.15"
camino = "1.0"

[build-dependencies]
rustc-private-link = { path = "../rustc-private-link" }

[package.metadata.rust-analyzer] 
rustc_private = true
